/// Flutter icons Shorts
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Shorts
///      fonts:
///       - asset: fonts/Shorts.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class ShortsBlank {
  ShortsBlank._();

  static const _kFontFam = 'ShortsBlank';
  static const String? _kFontPkg = null;

  static const IconData shorts = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
